import BUY_DESO from '../images/buy_deso.svg';
import DEQUEST_SOLO from '../images/dequest-solo.svg';
import DEQUEST from '../images/dequest.svg';
import DIAMOND_NAV from '../images/diamond-nav.svg';
import HOME from '../images/home.svg';
import PROFILE_NAV from '../images/profile-nav.svg';
import QA_MAIN from '../images/qa-main.svg';
import SETTINGS from '../images/settings.svg';
import SHARE from '../images/share.svg';
import UPVOTE from '../images/upvote.svg';
import DIAMOND from '../images/diamond.svg';

export const BUY_DESO = BUY_DESO;
export const DEQUEST_SOLO = DEQUEST_SOLO;
export const DEQUEST = DEQUEST;
export const DIAMOND_NAV = DIAMOND_NAV;
export const HOME = HOME;
export const PROFILE_NAV = PROFILE_NAV;
export const QA_MAIN = QA_MAIN;
export const SETTINGS = SETTINGS;
export const SHARE = SHARE;
export const UPVOTE = UPVOTE;
export const DIAMOND = DIAMOND;
